apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktjdus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktjdus
  template:
    metadata:
      labels:
        app: oktjdus
    spec:
      containers:
      - image: okteto.dev/oktjdus:latest
        name: oktjdus
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "da74d23c-a277-4fe3-b5a1-6fd240a80853"
        - name: Vless_Path
          value: "/efszw324"
        - name: Vmess_UUID
          value: "092568e8-7cb9-4b2a-b314-1116931c9776"
        - name: Vmess_Path
          value: "/kidu343"
        - name: Share_Path
          value: "/v2link"
